pragma ComponentBehavior: Bound
import QtQuick
import QtMultimedia
import org.kde.taskmanager as TaskManager

Item {
    id: stage

    property var wallpaper
    readonly property var config: stage.wallpaper.configuration
    readonly property bool loading: stage.front.status === Image.Loading
    readonly property bool covered: monitor.item ? (monitor.item as CoverMonitor).covered : false

    // front shows the current wallpaper, back loads the incoming one; they swap roles when a transition ends.
    property Slot front: slotA
    property Slot back: slotB

    property string current: ""
    property string pending: ""
    property string shader: "fade"
    readonly property var transitionNames: ["bounce", "CircleCrop", "circleopen", "ColourDistance", "crosshatch", "crosswarp", "Directional", "DirectionalScaled", "directionalwipe", "Dreamy", "fadecolor", "fade", "GlitchDisplace", "GlitchMemories", "morph", "parametric_glitch", "perlin", "pixelize", "PolkaDotsCurtain", "PuzzleRight", "Radial", "randomsquares", "ripple", "wind", "wipeDown", "wipeLeft", "wipeRight", "wipeUp", "circle", "crazy-parametric", "dissolve", "flyeye", "glass-warp", "glitch", "heat-melt", "ink-splash", "inkwell-drop", "overexposure", "pixelfade-wave", "plasma-flow", "polar-function", "smoke", "snap", "soft-warp-fade", "static-fade", "voronoi-shatter", "wave-warp"] // generated by build-shaders.sh

    readonly property string image: stage.config.Image
    onImageChanged: stage.show(stage.image)
    Component.onCompleted: stage.show(stage.image)

    function pickTransition() {
        let want = stage.config.Transition;
        if (want !== "random" && stage.transitionNames.indexOf(want) >= 0)
            return want;
        return stage.transitionNames[Math.floor(Math.random() * stage.transitionNames.length)];
    }

    function show(url) {
        url = String(url || "");
        if (url === stage.current)
            return;
        if (anim.running)
            stage.finish();
        stage.current = url;
        if (url === "") {
            stage.pending = "";
            stage.front.source = "";
            stage.back.source = "";
            return;
        }
        if (stage.front.status === Image.Null || stage.front.status === Image.Error) {
            stage.pending = "";
            stage.back.source = "";
            stage.front.source = url;
            return;
        }
        stage.shader = stage.pickTransition();
        fx.seed = Math.random();
        stage.pending = url;
        stage.back.source = url;
    }

    // Deferred per slot: slotStatus() may clear source, which would re-enter the Slot's status binding.
    function slotAStatus() {
        stage.slotStatus(slotA);
    }
    function slotBStatus() {
        stage.slotStatus(slotB);
    }

    function slotStatus(slot) {
        if (slot !== stage.back || stage.pending === "")
            return;
        if (slot.status === Image.Ready) {
            stage.pending = "";
            fx.progress = 0;
            anim.restart();
        } else if (slot.status === Image.Error) {
            stage.pending = "";
            slot.source = "";
        }
    }

    // Swap and reset in one call so no frame shows the old image; clearing the old slot frees its texture.
    function finish() {
        anim.stop();
        const shown = stage.back;
        stage.back = stage.front;
        stage.front = shown;
        fx.progress = 0;
        stage.back.source = "";
    }

    component Video: Item {
        id: clip

        property url source
        property int fillMode: Image.PreserveAspectCrop
        property bool playing: true
        readonly property int mediaStatus: player.mediaStatus

        onPlayingChanged: {
            if (clip.playing)
                player.play();
            else
                player.pause();
        }

        VideoOutput {
            id: out
            anchors.fill: parent
            fillMode: clip.fillMode === Image.Stretch ? VideoOutput.Stretch : clip.fillMode === Image.PreserveAspectCrop ? VideoOutput.PreserveAspectCrop : VideoOutput.PreserveAspectFit
        }

        MediaPlayer {
            id: player
            source: clip.source
            videoOutput: out
            loops: MediaPlayer.Infinite
            Component.onCompleted: if (clip.playing)
                player.play()
        }
    }

    component Slot: Item {
        id: slot

        property url source
        property int fillMode: Image.PreserveAspectCrop
        property bool playing: true
        readonly property bool isVideo: /\.(mp4|mkv|mov|webm)$/i.test(String(slot.source))
        readonly property Video video: videoLoader.item as Video
        // BufferedMedia is the first state with frames on screen, so a transition never starts on a black frame.
        readonly property int status: !slot.isVideo ? image.status : !slot.video ? Image.Null : (slot.video.mediaStatus === MediaPlayer.NoMedia ? Image.Null : slot.video.mediaStatus === MediaPlayer.InvalidMedia ? Image.Error : (slot.video.mediaStatus === MediaPlayer.BufferedMedia || slot.video.mediaStatus === MediaPlayer.EndOfMedia) ? Image.Ready : Image.Loading)

        Image {
            id: image
            anchors.fill: parent
            source: slot.isVideo ? "" : slot.source
            fillMode: slot.fillMode
            asynchronous: true
            cache: false
            sourceSize: Qt.size(width * slot.Screen.devicePixelRatio, height * slot.Screen.devicePixelRatio)
        }

        Loader {
            id: videoLoader
            anchors.fill: parent
            active: slot.isVideo
            sourceComponent: Video {
                source: slot.source
                fillMode: slot.fillMode
                playing: slot.playing
            }
        }
    }

    component CoverMonitor: Item {
        id: monitor

        property bool covered: false

        function update() {
            for (let i = 0; i < tasks.count; i++) {
                const idx = tasks.index(i, 0);
                if (tasks.data(idx, TaskManager.AbstractTasksModel.IsWindow) && (tasks.data(idx, TaskManager.AbstractTasksModel.IsMaximized) || tasks.data(idx, TaskManager.AbstractTasksModel.IsFullScreen))) {
                    monitor.covered = true;
                    return;
                }
            }
            monitor.covered = false;
        }

        TaskManager.VirtualDesktopInfo {
            id: desktopInfo
        }

        TaskManager.ActivityInfo {
            id: activityInfo
        }

        TaskManager.TasksModel {
            id: tasks
            groupMode: TaskManager.TasksModel.GroupDisabled
            filterByVirtualDesktop: true
            virtualDesktop: desktopInfo.currentDesktop
            filterByActivity: true
            activity: activityInfo.currentActivity
            filterByScreen: true
            screenGeometry: Qt.rect(monitor.Screen.virtualX, monitor.Screen.virtualY, monitor.Screen.width, monitor.Screen.height)
            filterMinimized: true
            filterHidden: true
            onDataChanged: Qt.callLater(monitor.update)
            onCountChanged: Qt.callLater(monitor.update)
        }
    }

    Slot {
        id: slotA
        anchors.fill: parent
        fillMode: stage.config.FillMode
        playing: !stage.covered
        onStatusChanged: Qt.callLater(stage.slotAStatus)
    }

    Slot {
        id: slotB
        anchors.fill: parent
        fillMode: stage.config.FillMode
        playing: !stage.covered
        onStatusChanged: Qt.callLater(stage.slotBStatus)
    }

    // The greeter has no task list, so there the wallpaper always plays.
    Loader {
        id: monitor
        active: Qt.application.name === "plasmashell"
        sourceComponent: CoverMonitor {}
    }

    ShaderEffectSource {
        id: fromSource
        sourceItem: stage.front
        hideSource: true
    }

    ShaderEffectSource {
        id: toSource
        sourceItem: stage.back
        hideSource: true
    }

    ShaderEffect {
        id: fx
        anchors.fill: parent
        property variant from: fromSource
        property variant to: toSource
        property real progress: 0
        property real ratio: width / Math.max(1, height)
        property real seed: 0
        property vector2d size: Qt.vector2d(width, height)
        fragmentShader: Qt.resolvedUrl("../shaders/" + stage.shader + ".frag.qsb")

        NumberAnimation on progress {
            id: anim
            running: false
            from: 0
            to: 1
            duration: stage.config.Duration
            onFinished: stage.finish()
        }
    }
}
