#!/usr/bin/env bash
# Bakes every transition body into contents/shaders/<name>.frag.qsb, then writes the name list
# into Stage.qml (live via the stamp) and contents/ui/transitions.js (config page).
# transitions/ holds gl-transitions bodies, niri/ holds Niri close_color bodies; each family has
# its own prelude/postlude. Outputs are committed; installing needs no qsb.
set -euo pipefail

PKG="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/org.serpantinum.wallpaper"
SHADERS="$PKG/contents/shaders"
STAGE="$PKG/contents/ui/Stage.qml"
QSB="${QSB:-/usr/lib/qt6/bin/qsb}"

[ -x "$QSB" ] || { echo "qsb not found at $QSB (qt6-shadertools)" >&2; exit 1; }

names=()
bake() {   # bake <family dir> <prelude> <postlude>
    local body name tmp n
    for body in "$SHADERS/$1"/*.glsl; do
        name="$(basename "$body" .glsl)"
        for n in "${names[@]}"; do
            [ "$n" != "$name" ] || { echo "duplicate transition name: $name" >&2; exit 1; }
        done
        tmp="$(mktemp --suffix=.frag)"
        # gl-transitions parameters are `uniform T x; // = default`; Vulkan GLSL has no loose uniforms.
        {
            cat "$SHADERS/$2"
            sed -E 's|^[[:space:]]*uniform[[:space:]]+([A-Za-z0-9]+)[[:space:]]+([A-Za-z_][A-Za-z0-9_]*)[[:space:]]*;[[:space:]]*//[[:space:]]*=[[:space:]]*(.*[^[:space:]])[[:space:]]*$|const \1 \2 = \3;|' "$body"
            cat "$SHADERS/$3"
        } > "$tmp"
        "$QSB" --qt6 -o "$SHADERS/$name.frag.qsb" "$tmp"
        rm -f "$tmp"
        names+=("$name")
        echo "built $name"
    done
}

bake transitions prelude.glsl postlude.glsl
bake niri prelude-niri.glsl postlude-niri.glsl

list=""
for n in "${names[@]}"; do list+="${list:+, }\"$n\""; done

sed -i -E "s|^([[:space:]]*readonly property var transitionNames: ).*$|\1[$list] // generated by build-shaders.sh|" "$STAGE"
grep -qF "transitionNames: [$list]" "$STAGE" || { echo "Stage.qml list line not found" >&2; exit 1; }

{
    printf '.pragma library\n'
    printf '// Generated by build-shaders.sh from contents/shaders/transitions/*.glsl and niri/*.glsl\n'
    printf 'var names = [%s];\n' "$list"
} > "$PKG/contents/ui/transitions.js"
echo "wrote ${#names[@]} names to Stage.qml and transitions.js"
